declare module 'react-native-syntax-highlighter';
declare module 'react-syntax-highlighter/styles/hljs';

declare const FIREBASE_API_KEY: string;
declare const BUILD_TARGET: string;
declare const BROWSER_CLIENT_ID: string;
declare const EXTENSION_CLIENT_ID: string;
declare const FIREBASE_AUTH_DOMAIN: string;
declare const FIREBASE_PROJECT_ID: string;
declare const FIREBASE_STORAGE_BUCKET: string;
declare const FIREBASE_MESSAGING_SENDER_ID: string;
declare const FIREBASE_APP_ID: string;
declare const FIREBASE_MEASUREMENT_ID: string;
declare const WEB3AUTH_ID: string;
declare const GATEFI_ENDPOINT: string;
declare const GATEFI_MERCHANT_ID: string;
declare const GRAPHQL_ENDPOINT: string;
declare const PIXEVERSE_ENDPOINT: string;
declare const PIXEVERSE_ORIGIN: string;
declare const PIXEVERSE_URL: string;
declare const SOLANA_CLUSTER_URL: string;
