export enum ModalId {
	Error = 'Error',
	Logout = 'Logout',
	Send = 'Send',
	Receive = 'Receive',
	Swap = 'Swap',
	Notification = 'Notification',
	RemoveLayout = 'RemoveLayout',
	RequirePasscode = 'RequirePasscode',
	TransactionDetails = 'TransactionDetails',
	QRScanner = 'QRScanner',
	ReferralLeaderBoard = 'ReferralLeaderBoard',
	LoyaltyPartnerQuest = 'LoyaltyPartnerQuest',
	LoyaltyHistory = 'LoyaltyHistory',
}
