name: Release on CloudFront
on:
  push:
    branches:
      - "main"
      - "dev"

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CI: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/

      - name: Set branch name
        id: branch
        run: echo "::set-output name=BRANCH_NAME::${GITHUB_REF##*/}"

      - name: Install metacraft-cli
        run: npm i --location=global @metacraft/cli

      - name: Install dependencies
        run: yarn

      - name: Execute eslint
        run: yarn lint

      - name: Run test cases
        run: yarn test

      - name: Generate Terraform script
        run: yarn gen ${GITHUB_REF##*/}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Extract Terraform output
        run: echo $(terraform output -json) > tf-output.json

      - name: Build
        run: yarn build
        env:
          gitBranch: ${{ steps.branch.outputs.BRANCH_NAME }}

      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_bucket: "walless-${{ steps.branch.outputs.BRANCH_NAME }}"
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          source_dir: apps/home/metacraft
          destination_dir: ''

      - name: Invalidate CloudFront cache
        run: yarn invalidate ${GITHUB_REF##*/}
